const  types = { 
    FETCH_CONTACTS : "FETCH_CONTACTS", 
    GET_CONTACT:"GET_CONTACT",
    GET_RATE:"GET_RATE",
    GET_STATICS1:"GET_STATICS1",
    GET_STATICS2:"GET_STATICS2",
    GET_USER:"GET_USER"


 
};
export default types;